New upstream version 2.4.17+caldav~beta10

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -648,6 +648,8 @@ JSON_LIBS
 JSON_CFLAGS
 DKIM_LIBS
 DKIM_CFLAGS
+ICU_LIBS
+ICU_CFLAGS
 SQLITE3_LIBS
 SQLITE3_CFLAGS
 ICAL_LIBS
@@ -845,6 +847,8 @@ ICAL_CFLAGS
 ICAL_LIBS
 SQLITE3_CFLAGS
 SQLITE3_LIBS
+ICU_CFLAGS
+ICU_LIBS
 JSON_CFLAGS
 JSON_LIBS'
 
@@ -1552,6 +1556,8 @@ Some influential environment variables:
               C compiler flags for SQLITE3, overriding pkg-config
   SQLITE3_LIBS
               linker flags for SQLITE3, overriding pkg-config
+  ICU_CFLAGS  C compiler flags for ICU, overriding pkg-config
+  ICU_LIBS    linker flags for ICU, overriding pkg-config
   JSON_CFLAGS C compiler flags for JSON, overriding pkg-config
   JSON_LIBS   linker flags for JSON, overriding pkg-config
 
@@ -9064,6 +9070,8 @@ ENABLE_HTTP=no
 # Check whether --enable-http was given.
 if test "${enable_http+set}" = set; then :
   enableval=$enable_http; ENABLE_HTTP=$enableval
+else
+   ENABLE_RSS=no ENABLE_DAV=no
 fi
 
 
@@ -9430,6 +9438,167 @@ $as_echo "#define WITH_DAV /**/" >>confdefs.h
 
 
 
+      cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+#include <ical.h>
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "ICAL_SCHEDULESTATUS_PARAMETER" >/dev/null 2>&1; then :
+
+$as_echo "#define HAVE_SCHEDULING_PARAMS /**/" >>confdefs.h
+
+fi
+rm -f conftest*
+
+
+      cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+#include <ical.h>
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "ICAL_VAVAILABILITY_COMPONENT" >/dev/null 2>&1; then :
+
+$as_echo "#define HAVE_VAVAILABILITY /**/" >>confdefs.h
+
+fi
+rm -f conftest*
+
+
+      cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+#include <ical.h>
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "ICAL_VPOLL_COMPONENT" >/dev/null 2>&1; then :
+
+$as_echo "#define HAVE_VPOLL /**/" >>confdefs.h
+
+fi
+rm -f conftest*
+
+
+      ENABLE_RSCALE=yes
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for ICU" >&5
+$as_echo_n "checking for ICU... " >&6; }
+
+if test -n "$ICU_CFLAGS"; then
+    pkg_cv_ICU_CFLAGS="$ICU_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"icu-i18n\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "icu-i18n") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_ICU_CFLAGS=`$PKG_CONFIG --cflags "icu-i18n" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$ICU_LIBS"; then
+    pkg_cv_ICU_LIBS="$ICU_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"icu-i18n\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "icu-i18n") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_ICU_LIBS=`$PKG_CONFIG --libs "icu-i18n" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        ICU_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "icu-i18n" 2>&1`
+        else
+	        ICU_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "icu-i18n" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$ICU_PKG_ERRORS" >&5
+
+	ENABLE_RSCALE=no
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	ENABLE_RSCALE=no
+else
+	ICU_CFLAGS=$pkg_cv_ICU_CFLAGS
+	ICU_LIBS=$pkg_cv_ICU_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+fi
+      if test "$ENABLE_RSCALE" != no; then
+
+
+	 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for icalrecurrencetype_rscale_supported_calendars in -lical" >&5
+$as_echo_n "checking for icalrecurrencetype_rscale_supported_calendars in -lical... " >&6; }
+if ${ac_cv_lib_ical_icalrecurrencetype_rscale_supported_calendars+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lical  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char icalrecurrencetype_rscale_supported_calendars ();
+int
+main ()
+{
+return icalrecurrencetype_rscale_supported_calendars ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_ical_icalrecurrencetype_rscale_supported_calendars=yes
+else
+  ac_cv_lib_ical_icalrecurrencetype_rscale_supported_calendars=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_ical_icalrecurrencetype_rscale_supported_calendars" >&5
+$as_echo "$ac_cv_lib_ical_icalrecurrencetype_rscale_supported_calendars" >&6; }
+if test "x$ac_cv_lib_ical_icalrecurrencetype_rscale_supported_calendars" = xyes; then :
+
+$as_echo "#define HAVE_RSCALE /**/" >>confdefs.h
+
+fi
+
+      fi
+
 
 
 # Check whether --with-opendkim-libdir was given.
@@ -9645,7 +9814,7 @@ ENABLE_REPLICATION=no
 if test "${enable_replication+set}" = set; then :
   enableval=$enable_replication; ENABLE_REPLICATION=$enableval
         if test "$ENABLE_REPLICATION" != no; then
-	  IMAP_PROGS="$IMAP_PROGS sync_client sync_server sync_reset"
+	  IMAP_PROGS="$IMAP_PROGS sync_client sync_reset"
         fi
 fi
 
