Rewrite init.d script to make use start-stop-daemon and lsb init functions as much as possible;  Also implement much more graceful stop for cyrmaster - sending QUIT/TERM/KILL with timeouts and using sync_shutdown_file for sync_client

diff --git a/debian/cyrus-common.cyrus-imapd.init b/debian/cyrus-common.cyrus-imapd.init
--- a/debian/cyrus-common.cyrus-imapd.init
+++ b/debian/cyrus-common.cyrus-imapd.init
@@ -18,17 +18,35 @@
 #
 #		Copyright 2001-2005 by Henrique de Moraes Holschuh <hmh@debian.org>
 #		Various modifications done by Sven Mueller <debian@incase.de>
+#               Updated with regards to current /etc/init.d/skeleon by Ondřej Surý <ondrej@sury.org>
+#
 #		Distributed under the GPL version 2
 
 # Make sure we get sane results on borked locales
 LC_ALL=C
 export LC_ALL
 
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+NAME=cyrmaster
+DAEMON=/usr/sbin/${NAME}
+PIDFILE="/var/run/${NAME}.pid"
+DESC="Cyrus IMAPd"
+
+SYNC_CLIENT=/usr/lib/cyrus/bin/sync_client
+SYNCSHUTDOWN="$([ -r /etc/imapd.conf ] && (grep sync_shutdown_file /etc/imapd.conf|awk '{print $2}'))"
+
+# Check if Cyrus is installed (vs. removed but not purged)
+test -x "$DAEMON" || exit 0
+
 # Overridable defaults
 unset CYRUS_VERBOSE
 unset LISTENQUEUE
 unset CONF
 unset MASTERCONF
+
+# Read configuration variable file if it is present
 [ -r /etc/default/cyrus-imapd ] && . /etc/default/cyrus-imapd
 
 [ "x${CYRUS_VERBOSE}" != "x" ] && export CYRUS_VERBOSE
@@ -38,20 +56,19 @@ OPTIONS="${OPTIONS} -d"
 [ "x${MASTERCONF}" != "x" ] && OPTIONS="-M ${MASTERCONF} ${OPTIONS}"
 [ "x${LISTENQUEUE}" != "x" ] && OPTIONS="-l ${LISTENQUEUE} ${OPTIONS}"
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DAEMON=/usr/sbin/cyrmaster
-NAME=cyrmaster
-[ "x${PIDFILE}" = "x" ] && PIDFILE="/var/run/${NAME}.pid"
-DESC="Cyrus IMAPd"
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-# Check if Cyrus is installed (vs. removed but not purged)
-test -x ${DAEMON} || exit 0
-grep -qE '^PACKAGE_VERSION[[:blank:]]+([0-9]+:|)2[.][24]' \
-	/usr/lib/cyrus/cyrus-hardwired-config.txt >/dev/null 2>&1 || exit 0
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
 
-set -e
-
-START="--start --quiet --pidfile ${PIDFILE} --exec ${DAEMON} --name ${NAME} -- ${OPTIONS}"
+check_hardwired_config() {
+    grep -qE '^PACKAGE_VERSION[[:blank:]]+([0-9]+:|)2[.][24]' \
+	/usr/lib/cyrus/cyrus-hardwired-config.txt >/dev/null 2>&1
+    return $?
+}
 
 verifydb() {
    while read -r DBKEY DBVALUE ; do
@@ -66,171 +83,189 @@ createdir() {
 # $2 = group
 # $3 = permissions (octal)
 # $4 = path to directory
-	[ -d "$4" ] || mkdir -p "$4"
-	chown -c -h "$1:$2" "$4"
-	chmod -c "$3" "$4"
+    [ "$VERBOSE" = "yes" ] && OPT="-c"
+    [ -d "$4" ] || mkdir -p "$4"
+    chown $OPT -h "$1:$2" "$4"
+    chmod $OPT "$3" "$4"
 }
 
 missingstatoverride () {
-	echo "$0: You are missing a dpkg-statoverride on $1.  Add it." >&2
-	exit 1
+    echo "$0: You are missing a dpkg-statoverride on $1.  Add it." >&2
+    exit 1
 }
 
 fixdirs () {
-	dir=`dpkg-statoverride --list /var/run/cyrus` \
+	dir=$(dpkg-statoverride --list /var/run/cyrus) \
 		|| missingstatoverride /var/run/cyrus
 	[ -z "$dir" ] \
 		|| createdir $dir
-	dir=`dpkg-statoverride --list /var/run/cyrus/socket` \
+	dir=$(dpkg-statoverride --list /var/run/cyrus/socket) \
 		|| missingstatoverride /var/run/cyrus/socket
 	[ -z "$dir" ] \
 		|| createdir $dir
 }
 
-check_status () {
-	if [ "$1" = "verbose" ]; then
-		PRINTIT=echo
-	else
-		PRINTIT=true 
-	fi
-	if [ ! -f ${PIDFILE} ]; then
-		# using [c] in the grep avoids catching the grep 
-		# process itself
-		if ps auxww | grep -qE 'usr/sbin/[c]yrmaster' ; then
-			# Damn, PID file doesn't exist, but cyrmaster process
-			# exists. Though strictly speaking, we should not
-			# do this, reconstruct the PID file here.
-			pidof /usr/sbin/cyrmaster > /dev/null 2>&1 \
-			&& pidof /usr/sbin/cyrmaster > ${PIDFILE}
-			${PRINTIT} "cyrmaster running with PID `cat ${PIDFILE}`"
-			return 0
-		fi
-	fi	
-	if [ -s ${PIDFILE} ] && kill -0 `cat ${PIDFILE}` > /dev/null 2>&1; then
-		${PRINTIT} "cyrmaster running with PID `cat ${PIDFILE}`"
-		return 0
-	else
-		# the PID file might simply not match the cyrmaster process.
-		if pidof /usr/sbin/cyrmaster > /dev/null 2>&1 ; then
-			# go ahead and fix it
-			pidof /usr/sbin/cyrmaster > ${PIDFILE}
-			${PRINTIT} "cyrmaster running with PID `cat ${PIDFILE}`"
-			return 0
-		else
-			# no process and/or no PID file, return failure
-			${PRINTIT} "cyrmaster not running with"
-			return 1
-		fi
-	fi
-	# this point should never be reached, return unknown status if it 
-	# is anyway
-	return 4
+#
+# Function that checks consistency of used database backends
+#
+check_database_backends() {
+    # Verify consistency of database backends
+    [ -f /usr/lib/cyrus/cyrus-db-types.active ] && {
+        # is it safe to start cyrmaster? compare "key value" pairs
+        # from the (old) active database types file with the new one
+	( sort -u /usr/lib/cyrus/cyrus-db-types.active \
+	    | grep DBENGINE \
+	    | verifydb /usr/lib/cyrus/cyrus-db-types.txt \
+	    ) && {
+	    return 1
+	}
+    }
+    return 0
 }
 
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+	|| return 1
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+	$OPTIONS \
+	|| return 2
+
+    # cyrmaster is not running
+    pidofproc $DAEMON >/dev/null || return 2
+}
+
+sync_stop () {
+    if [ -e $SYNC_CLIENT ]; then
+	# is sync_client running?
+	pidofproc $SYNC_CLIENT >/dev/null || return 1
+
+        # Check if the sync file is set and use it is defined
+	if [ -n "$SYNCSHUTDOWN" ]; then
+	    touch "$SYNCSHUTDOWN" || return 2
+	    start-stop-daemon --stop --quiet --retry 0/10 --exec $SYNC_CLIENT
+	    rm -f $SYNCSHUTDOWN
+	fi
+    fi
+    return 0
+}
+
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+
+    sync_stop
+    [ "$?" = 2 ] && return 2
+    
+    start-stop-daemon --stop --quiet --retry=QUIT/30/TERM/10/KILL/5 --pidfile $PIDFILE --name $NAME
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+
+    # cyrmaster is still running
+    pidofproc $DAEMON >/dev/null && return 2
+
+    # Many daemons don't delete their pidfiles when they exit.
+    rm -f $PIDFILE
+    return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+    return 0
+}
+
+# Check for the sanity of the cyrus-imapd environment
+if ! check_hardwired_config; then
+    echo "$0: cyrus-hardwired-config.txt doesn't contain current version"
+    echo "$0: of the package (2.2 or 2.4)"
+    exit 1
+fi
+
+if ! check_database_backends; then
+    echo "$0: Database backends mismatch! You must manually" 1>&2
+    echo "$0: verify and update the Cyrus databases to the" 1>&2
+    echo "$0: new backends." 1>&2
+    echo "$0: Please refer to /usr/share/doc/cyrus-common/README.Debian" 1>&2
+    echo "$0: for instructions." 1>&2
+    echo
+    echo "$0: Cyrmaster not started."
+    exit 6
+fi
+
 case "$1" in
-  start)
-	# Verify consistency of database backends
-	[ -f /usr/lib/cyrus/cyrus-db-types.active ] && {
-		# is it safe to start cyrmaster? compare "key value" pairs
-		# from the (old) active database types file with the new one
-		( sort -u /usr/lib/cyrus/cyrus-db-types.active \
-		  | grep DBENGINE \
-		  | verifydb /usr/lib/cyrus/cyrus-db-types.txt \
-		) && {
-		    echo "$0: Database backends mismatch! You must manually" 1>&2
-		    echo "$0: verify and update the Cyrus databases to the" 1>&2
-		    echo "$0: new backends." 1>&2
-		    echo "$0: Please refer to /usr/share/doc/cyrus-common/README.Debian" 1>&2
-		    echo "$0: for instructions." 1>&2
-		    echo
-		    echo "$0: Cyrmaster not started."
-		    exit 6
-		}
-	}
-	echo -n "Starting ${DESC}: "
+    start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	fixdirs
-	if check_status ; then
-		echo "${DAEMON} already running."
-		exit 0
-	fi
-	if start-stop-daemon ${START} >/dev/null 2>&1 ; then
-		echo "$NAME."
-	else
-		if ! check_status ; then
-			echo "(failed)."
-			exit 1
-		fi
-	fi
+	do_start
+	case "$?" in
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-  stop)
-	echo -n "Stopping $DESC: "
-	if start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
-		--name ${NAME} --quiet --startas $DAEMON >/dev/null 2>&1 ; then
-		echo "$NAME."
-		rm -f ${PIDFILE}
-		exit 0
-	else
-		# process running?
-		if check_status; then
-			# Yes, report failure.
-			echo "(failed)."
-			exit 1
-		else
-			# No, return as if stopped a running process 
-			# successfully.
-			echo "."
-			rm -f ${PIDFILE}
-			exit 0
-		fi
-	fi
+    stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   reload|force-reload)
-	echo "Reloading $DESC configuration files."
-	if start-stop-daemon --stop --signal 1 --quiet \
-		--name ${NAME} --pidfile /var/run/$NAME.pid >/dev/null 2>&1 ; then
-		exit 0
-	else
-		exit 1
-	fi
+	log_daemon_msg "Reloading $DESC" "$NAME"
+	do_reload
+	log_end_msg $?
   	;;
   restart)
-  	$0 stop && {
-	  echo -n "Waiting for complete shutdown..."
-	  i=5
-	  while [ $i -gt 0 ] ; do
-	  	# exit look when server is not running
-	  	check_status || break
-		sleep 2s
-		i=$(($i - 1))
-		echo -n "."
-	  done
-	  [ $i -eq 0 ] && {
-	  	echo
-		echo "fatal: incomplete shutdown detected, aborting."
-		exit 1
-	  }
-	  echo
-	}
-	exec $0 start
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	    0|1)
+		do_start
+		case "$?" in
+		    0) log_end_msg 0 ;;
+		    1) log_end_msg 1 ;; # Old process is still running
+		    *) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
   status)
-  	check_status verbose
-	exit $?
-	;;
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
   try-restart)
-  	check_status
-	if [ "$?" -eq 0 ]; then
-		exec $0 restart
-	else
-  		# LSB says to return 0 in try-restart if the service is
-		# not running.
-		exit 0
-	fi
+  	pidofproc "$DAEMON" && exec $0 restart
 	;;
   *)
-	echo "Usage: $0 {start|stop|restart|reload|force-reload}" 1>&2
-	exit 1
+	echo "Usage: $0 {start|stop|status|restart|reload|force-reload|try-restart}" 1>&2
+	exit 3
 	;;
 esac
 
-exit 0
+:
