Rework postinst files to use dpkg-trigger to run cyrus-makedirs and (re)start cyrmaster

diff --git a/debian/cyrus-common.postinst b/debian/cyrus-common.postinst
--- a/debian/cyrus-common.postinst
+++ b/debian/cyrus-common.postinst
@@ -5,9 +5,6 @@
 #
 # see: dh_installdeb(1)
 
-# debconf hook
-. /usr/share/debconf/confmodule
-
 set -e
 
 # summary of how this script can be called:
@@ -32,24 +29,6 @@ export PATH=/sbin:/usr/sbin:/bin:/usr/bin
 CONF="/etc/imapd.conf"
 CYRUS_CONFIG_DIR="/var/lib/cyrus"
 [ -r /etc/default/cyrus-imapd ] && . /etc/default/cyrus-imapd
-
-verifydb() {
-   while read -r DBKEY DBVALUE ; do
-	match=`LC_ALL=C gawk "/^${DBKEY}[[:blank:]]/ { print \\$2 }" < $1`
-	[ "x${match}" != "x${DBVALUE}" ] && return 0
-   done
-   return 1
-}
-
-verifydbkey() {
-   while read -r DBKEY DBVALUE ; do
-	if [ "${DBKEY}" = "$2" ] ; then
-	    match=`LC_ALL=C gawk "/^${DBKEY}[[:blank:]]/ { print \\$2 }" < $1`
-	    [ "x${match}" != "x${DBVALUE}" ] && return 0
-	fi
-   done
-   return 1
-}
 
 getconf () {
 	confvalue=`sed --silent -e "/^[[:blank:]]*${1}:/ { \
@@ -91,76 +70,35 @@ case "$1" in
 	# Add user cyrus to group SASL, if such group exists
 	adduser cyrus sasl || true
 
-	# Convert the spool to the proper mode, if needed (autodetects
-	# only Debian's default spool, this codepath is meant for package
-	# upgrades only)
-	# DISABLED, since rehash seems busted
-	#[ -d /var/spool/cyrus/mail/A ] && {
-	#	echo Converting spools to basic hash scheme...
-	#	#su - cyrus -c "/usr/lib/cyrus/upgrade/rehash basic"
-	#	start-stop-daemon --start --exec /usr/lib/cyrus/upgrade/rehash --chuid cyrus:mail --verbose -- basic
-	#}
+    ;;
 
-	# Parse imapd.conf and generate all required directories...
-	# also kill any left over squatter indexes
-	# only run if old upstream version is lower than the new upstream
-	# version (or if its a fresh install)
-	if [ "$2" = "" ] || dpkg --compare-versions "$( echo $2 | cut -d- -f2)" lt "2.4.14" ; then
-		cyrus-makedirs --cleansquat
-	fi
+    triggered)
+        case "$2" in
+	    # Restart cyrus everytime a new script is installed to /usr/lib/cyrus/bin
+            /usr/lib/cyrus/bin)
+        	# Register initscript, and start it (it is ok if start fails)
+        	[ -x /etc/init.d/cyrus-imapd ] && {
+        		update-rc.d cyrus-imapd defaults >/dev/null
+			invoke-rc.d cyrus-imapd stop || true
+        		invoke-rc.d cyrus-imapd start || true
+        	}
+            ;;
 
-	# Add USERDENY database if doesn't exist
-	getconf configdirectory ${CYRUS_CONFIG_DIR}
-	CYRUS_CONFIG_DIR=$result
+	    cyrus-makedirs)
+        	cyrus-makedirs --cleansquat
 
-	userdeny_database=${CYRUS_CONFIG_DIR}"/user_deny.db"
-	if [ ! -e ${userdeny_database} ]; then
-		touch ${userdeny_database}
-		chmod 600 ${userdeny_database}
-		chown cyrus:mail ${userdeny_database}
-	fi
+        	# Add USERDENY database if doesn't exist
+        	getconf configdirectory ${CYRUS_CONFIG_DIR}
+        	CYRUS_CONFIG_DIR=$result
 
-	# Deal with database type information
-	if [ -f /usr/lib/cyrus/cyrus-db-types.active ] ; then
-		# is it safe to start cyrmaster? compare "key value" pairs
-		# from the (old) active database types file with the new one
-		if verifydb /usr/lib/cyrus/cyrus-db-types.txt \
-		    < /usr/lib/cyrus/cyrus-db-types.active ; then
-		    db_input high cyrus-common/warnbackendchange || true
-		    db_go || true
-		else
-		    cp -p /usr/lib/cyrus/cyrus-db-types.txt /usr/lib/cyrus/cyrus-db-types.active
-		    db_fset cyrus-common/warnbackendchange seen false || true
-		fi
-	else
-		[ -f /usr/lib/cyrus/cyrus-db-types.txt ] && \
-		  cp -p /usr/lib/cyrus/cyrus-db-types.txt /usr/lib/cyrus/cyrus-db-types.active
-		db_fset cyrus-common/warnbackendchange seen false || true
-	fi
-
-	# Deal with hardwired config changes
-	if [ -f /usr/lib/cyrus/cyrus-hardwired-config.active ] ; then
-		# do we need to do something about a spool hash type change
-		# if verifydbkey /usr/lib/cyrus/cyrus-hardwired-config.txt USE_DIR_FULL \
-		#    < /usr/lib/cyrus/cyrus-hardwired-config.active ; then
-		# ... (do hash conversion)...
-		# fi
-		cp -p /usr/lib/cyrus/cyrus-hardwired-config.txt \
-		      /usr/lib/cyrus/cyrus-hardwired-config.active
-	else
-		[ -f /usr/lib/cyrus/cyrus-hardwired-config.txt ] && \
-		  cp -p /usr/lib/cyrus/cyrus-hardwired-config.txt \
-		        /usr/lib/cyrus/cyrus-hardwired-config.active
-	fi
-
-	# No leaking of debconf file handles to the initscript stuff
-	db_stop
-
-	# Register initscript, and start it (it is ok if start fails)
-	[ -x /etc/init.d/cyrus-imapd ] && {
-		update-rc.d cyrus-imapd defaults >/dev/null
-		invoke-rc.d cyrus-imapd start || true
-	}
+        	userdeny_database=${CYRUS_CONFIG_DIR}"/user_deny.db"
+        	if [ ! -e ${userdeny_database} ]; then
+        		touch ${userdeny_database}
+        		chmod 600 ${userdeny_database}
+        		chown cyrus:mail ${userdeny_database}
+        	fi
+            ;;
+        esac
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -171,8 +109,6 @@ case "$1" in
         exit 0
     ;;
 esac
-
-db_stop
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
